services:
  - type: web
    name: ysport-backend
    env: node
    region: frankfurt
    buildCommand: |
      cd server
      npm install
    startCommand: |
      cd server
      node index.js
    envVars:
      - key: PORT
        value: 225
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: CORS_ORIGIN
        value: https://sport-liard.vercel.app
    healthCheckPath: /health
    autoDeploy: true
    branch: main
    disk:
      name: tmp
      mountPath: /tmp
      sizeGB: 1
  